#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
  then
		# Handle delete
    :
	else
		if test "$remote_oid" = "$zero"
    then
			# New branch
      :
		else
			# Update to existing branch
      :
		fi

    # Lint commits to be pushed
    zx scripts/lint-commit-messages.mjs --remote="$1" --branch="$local_ref"
	fi
done

exit 0
